/* COMPANYS */
export const GET_COMPANYS = "GET_COMPANYS"
export const GET_COMPANYS_SUCCESS = "GET_COMPANYS_SUCCESS"
export const GET_COMPANYS_FAIL = "GET_COMPANYS_FAIL"

/* COMPANYS PROFILE */
export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE"
export const GET_COMPANY_PROFILE_SUCCESS = "GET_COMPANY_PROFILE_SUCCESS"
export const GET_COMPANY_PROFILE_FAIL = "GET_COMPANY_PROFILE_FAIL"

/**
 * add COMPANY
 */
export const ADD_NEW_COMPANY = "ADD_NEW_COMPANY"
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS"
export const ADD_COMPANY_FAIL = "ADD_COMPANY_FAIL"

/**
 * Delete COMPANY
 */
export const DELETE_COMPANY = "DELETE_COMPANY"
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL"
